//Get All Persons Check
GET http://localhost:3001/api/persons HTTP/1.1

### //Get All Persons Check
GET http://localhost:3001/api/persons/4 HTTP/1.1

### //Get All Persons Check
GET http://localhost:3001/api/persons/someInvalidId HTTP/1.1

### //Get Info Check
GET http://localhost:3001/info HTTP/1.1


### //Get Unkonw Endpoint Request
GET http://localhost:3001/dogs HTTP/1.1

