//Get All Persons Check
GET http://localhost:3001/api/persons HTTP/1.1

###
//Get Specific Persons Check
GET http://localhost:3001/api/persons/1 HTTP/1.1

###
//Get Dammaged Request Check
GET http://localhost:3001/api/dogs HTTP/1.1